export const ADD_MEDICINE_REQUEST = "ADD_MEDICINE_REQUEST";
export const ADD_MEDICINE_SUCCESS = "ADD_MEDICINE_SUCCESS";
export const ADD_MEDICINE_FAIL = "ADD_MEDICINE_FAIL";

export const GET_MEDICINE_REQUEST = "GET_MEDICINE_REQUEST";
export const GET_MEDICINE_SUCCESS = "GET_MEDICINE_SUCCESS";
export const GET_MEDICINE_FAIL = "GET_MEDICINE_FAIL";

// export const GET_EXPIRE_MEDICINE_REQUEST = "GET_EXPIRE_MEDICINE_REQUEST";
// export const GET_EXPIRE_MEDICINE_SUCCESS = "GET_EXPIRE_MEDICINE_SUCCESS";
// export const GET_EXPIRE_MEDICINE_FAIL = "GET_EXPIRE_MEDICINE_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";